version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/src/main/java/dco/global/config/postgresql/data
    networks:
      - dco-network

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - dco-network

volumes:
  db_data:

networks:
  dco-network:
    driver: bridge